import { useRef, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { toPng } from 'html-to-image'
import type { Alert } from '../api/weatherApi'
import { formatTemp, formatWind, formatRain, type UnitSystem } from '../utils/units'

interface ShareModalProps {
  isOpen: boolean
  onClose: () => void
  locationName: string
  currentWeather: any
  alerts: Alert[]
  unit: UnitSystem
}

export default function ShareModal({
  isOpen,
  onClose,
  locationName,
  currentWeather,
  alerts,
  unit,
}: ShareModalProps) {
  const cardRef = useRef<HTMLDivElement>(null)
  const [downloading, setDownloading] = useState(false)
  const [copied, setCopied] = useState(false)

  if (!isOpen) return null

  const handleDownload = async () => {
    if (!cardRef.current) return
    setDownloading(true)
    try {
      const dataUrl = await toPng(cardRef.current, { quality: 0.95, pixelRatio: 2 })
      const link = document.createElement('a')
      link.download = `WeatherGPT-Advisory-${locationName}-${new Date().toISOString().split('T')[0]}.png`
      link.href = dataUrl
      link.click()
    } catch (err) {
      console.error('Failed to export advisory card:', err)
    } finally {
      setDownloading(false)
    }
  }

  const handleCopyText = () => {
    const text = `🌤️ *WeatherGPT Advisory for ${locationName}* (${new Date().toLocaleDateString('en-IN')})
🌡️ Temp: ${formatTemp(currentWeather?.temp_c ?? 30, unit)} (Feels like ${formatTemp(currentWeather?.feels_like_c ?? 30, unit)})
💨 Wind: ${formatWind(currentWeather?.wind_kmh ?? 10, unit)}
💧 Humidity: ${currentWeather?.humidity_pct ?? 60}%
🌧️ Rain: ${formatRain(currentWeather?.rain_mm ?? 0, unit)}
${alerts.length > 0 ? `⚠️ Alerts: ${alerts.map(a => `${a.icon} ${a.label}`).join(', ')}` : '✅ IMD Status: All Clear'}
🔗 Generated by WeatherGPT · SIH 26068`

    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 3000)
  }

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0, scale: 0.95 }}
          className="glass-card max-w-md w-full p-6 bg-slate-950/90 border border-white/20 shadow-2xl relative"
        >
          <div className="flex items-center justify-between pb-3 mb-4 border-b border-white/10">
            <h3 className="font-extrabold text-base text-white font-display flex items-center gap-2">
              <span>📲</span> Shareable Weather Advisory Card
            </h3>
            <button
              onClick={onClose}
              className="text-white/60 hover:text-white text-sm font-bold cursor-pointer"
            >
              ✕
            </button>
          </div>

          {/* WhatsApp / Social Branded Advisory Card to Capture */}
          <div
            ref={cardRef}
            className="p-5 rounded-2xl bg-gradient-to-br from-slate-900 via-indigo-950 to-slate-900 border border-white/20 text-white shadow-xl relative overflow-hidden"
          >
            {/* Ambient Lighting */}
            <div className="absolute -top-10 -right-10 w-32 h-32 bg-sky-500/20 rounded-full blur-2xl pointer-events-none" />
            <div className="absolute -bottom-10 -left-10 w-32 h-32 bg-amber-500/20 rounded-full blur-2xl pointer-events-none" />

            {/* Card Header */}
            <div className="flex items-center justify-between border-b border-white/15 pb-2.5 mb-3">
              <div className="flex items-center gap-2">
                <span className="text-2xl">🌦️</span>
                <div>
                  <h4 className="font-black text-sm tracking-tight text-white font-display">WeatherGPT</h4>
                  <p className="text-[9px] uppercase tracking-wider text-emerald-400 font-bold">Ministry of Earth Sciences / IMD</p>
                </div>
              </div>
              <span className="text-[10px] text-white/50 font-mono">
                {new Date().toLocaleDateString('en-IN', { month: 'short', day: 'numeric', year: 'numeric' })}
              </span>
            </div>

            {/* Main Location & Temp */}
            <div className="flex items-center justify-between my-2">
              <div>
                <h3 className="font-black text-xl text-white tracking-tight font-display flex items-center gap-1.5">
                  <span>📍</span> {locationName}
                </h3>
                <p className="text-xs text-white/70 font-semibold mt-0.5">
                  {currentWeather?.condition || 'Partly Cloudy'}
                </p>
              </div>
              <div className="text-right">
                <span className="text-3xl font-black text-white font-display">
                  {formatTemp(currentWeather?.temp_c ?? 30, unit)}
                </span>
                <p className="text-[10px] text-white/50">
                  Feels {formatTemp(currentWeather?.feels_like_c ?? 30, unit)}
                </p>
              </div>
            </div>

            {/* Metrics Row */}
            <div className="grid grid-cols-3 gap-2 my-3 p-2.5 rounded-xl bg-white/5 border border-white/10 text-center">
              <div>
                <p className="text-[9px] text-white/50 uppercase font-bold">Humidity</p>
                <p className="text-xs font-black text-white">{currentWeather?.humidity_pct ?? 60}%</p>
              </div>
              <div>
                <p className="text-[9px] text-white/50 uppercase font-bold">Wind</p>
                <p className="text-xs font-black text-white">{formatWind(currentWeather?.wind_kmh ?? 10, unit)}</p>
              </div>
              <div>
                <p className="text-[9px] text-white/50 uppercase font-bold">Rainfall</p>
                <p className="text-xs font-black text-white">{formatRain(currentWeather?.rain_mm ?? 0, unit)}</p>
              </div>
            </div>

            {/* Alert / Status Bar */}
            {alerts.length > 0 ? (
              <div className="p-2 rounded-xl bg-red-500/20 border border-red-500/30 text-xs text-red-200 flex items-center gap-2">
                <span>⚠️</span>
                <span className="font-bold text-[11px]">
                  {alerts[0].label}: {alerts[0].message}
                </span>
              </div>
            ) : (
              <div className="p-2 rounded-xl bg-emerald-500/20 border border-emerald-500/30 text-xs text-emerald-200 flex items-center gap-2">
                <span>🛡️</span>
                <span className="font-semibold text-[11px]">All Clear · Meteorological indices normal</span>
              </div>
            )}

            {/* Footer */}
            <div className="mt-3 pt-2 border-t border-white/10 flex items-center justify-between text-[9px] text-white/40">
              <span>Grounded AI Weather Intelligence</span>
              <span>SIH Problem 26068</span>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex items-center gap-3 mt-4">
            <button
              onClick={handleDownload}
              disabled={downloading}
              className="flex-1 glass-btn py-2.5 bg-indigo-600/80 hover:bg-indigo-500 text-white font-bold text-xs rounded-xl flex items-center justify-center gap-2 cursor-pointer shadow-lg"
            >
              <span>📥</span>
              <span>{downloading ? 'Exporting PNG...' : 'Download Image Card'}</span>
            </button>

            <button
              onClick={handleCopyText}
              className="glass-btn px-4 py-2.5 text-xs font-bold text-white rounded-xl flex items-center gap-1.5 cursor-pointer"
            >
              <span>{copied ? '✅' : '📋'}</span>
              <span>{copied ? 'Copied!' : 'Copy WhatsApp Text'}</span>
            </button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  )
}
